name: E2E Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v4
      
    - name:  Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        
    - name: Setup python
      uses: actions/setup-python@v5.2.0
      with:
        python-version: 3.12
        

    - name: Install deps
      run: |
        python -m pip install upgrade pip
        pip install -r requirements.txt

    - name: Browser Init
      run: |
        rfbbowser init
       
