name: E2E Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v4
      
  #  - name:  Setup node
  #    uses: actions/setup-node@v4
  #    with:
  #      node-version: 20
        
  #  - name: Setup python
  #    uses: actions/setup-python@v5.2.0
  #    with:
  #      python-version: 3.12

    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Browser Init
      run: |
        rfbrowser init
       
    - name: Run E2E
      run: |
        robot -d ./logs -i smoke tests

    - name: Robot Reporter
      uses: joonvena/robotframework-reporter-action@v2.4
      with:
        gh_access_token: ${{secrets.GITHUB_TOKEN}}
        report_path: logs
